### ISSUE TITLE
On Ubuntu 17.04 error on running cxf2ogr

### ISSUE THREAD

**Issue by marcobra** [bopen/bgeo.catasto#4]
Hi i'm tryng for the first time:

cxf2ogr AXXX_002500.CXF 

and i get this runtime error in my env, please tell the Ubuntu release you are using to develop i will install it, thank.

Traceback (most recent call last):
  File "/usr/local/bin/cxf2ogr", line 11, in <module>
    load_entry_point('bgeo.catasto', 'console_scripts', 'cxf2ogr')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/src/bgeo.catasto/bgeo/catasto/apps.py", line 13, in <module>
    @click.command()
AttributeError: module 'click' has no attribute 'command'

**Comment by marcobra** [comment]
No, invalid issue, in another ubuntu 17.04 less customized than my first one, it works

**Comment by marcobra** [comment]
I reopen issue: in Ubuntu 17.04, tested on several Ubuntu installation it give errors on running...
It works fine in Ubuntu 16.04

**Comment by alexamici** [comment]
I don't understand, the Click documentation uses `click.command` in the first example on the home page: http://click.pocoo.org/

Changing distribution should not be relevant unless there is a clash on the `click` name. Did you install click with pip or with apt-get?

**Comment by marcobra** [comment]
For the click error i tried with click and requirements installed in several mode:

1) from pip 

2) from apt-get

apt-cache policy python-click
python-click:
  Installato: 6.6-1
  Candidato:  6.6-1
  Tabella versione:
 *** 6.6-1 500
        500 http://archive.ubuntu.com/ubuntu zesty/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu zesty/main i386 Packages
        100 /var/lib/dpkg/status

3) also tried to "install" and run cxf2org using virtualenv

i always get the same error at runtime on click:command() very strange

if i test in my /tmp dir the first sample here http://click.pocoo.org/5/
it works without any click:command() error and just after testing this i redo a quick test of installed cxf2ogr i still get same error reported before.

The errors coming out are different from the first one i tested from the other Ubuntu 17.04 systems.
So i can give you mode details of different errors by sending separated report here.

Thank

**Comment by marcobra** [comment]
i'm closing this issue was not related to cxf2ogr code i've resolved by removing installed python3-click-package

sudo apt-get remove python3-click-package
